apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-12-26T12:56:28Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "2457208"
  uid: 26d7acec-811e-4507-9a8a-78eb53497e59
spec:
  containers:
  - image: nginx
    name: nginx
  nodeName: cka-cluster2-worker2 

