apiVersion: v1
kind: Pod
metadata: 
  name: nginx-exists
  labels:
    env: dev

spec: 
  containers:
  - name: nginx-exists
    image: nginx

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: Exists
