apiVersion: v1
kind: Pod
metadata: 
  name: nginx-new
  labels:
    env: dev

spec: 
  containers:
  - name: nginx-new
    image: nginx

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd  
