apiVersion: v1

kind: Service

metadata: 
  name: nodeport-svc
  labels:
    env: demo

spec:
  type: NodePort
  ports:
  - nodePort: 30001
    targetPort: 80
    port: 80
  selector:   #pod selector - label of the deployment pod
    env: demo










